#!/usr/bin/env bash

source /.rpm-helpers

set -e

git --version
VERSION="$(git --git-dir "${GO_SRC_PATH}/.git" describe --tags | sed 's/^v//')"
RPM_VER_BITS=$(gen-rpm-ver-bits "${VERSION}")
RPM_VERSION=$(echo "${RPM_VER_BITS}" | cut -f1 -d' ')
RPM_RELEASE_VERSION=$(echo "${RPM_VER_BITS}" | cut -f2 -d' ')


# Check if we're on a tagged version, change VERSION to dev build if not
if ! git --git-dir "${GO_SRC_PATH}/.git" describe --exact-match HEAD >/dev/null 2>&1; then
    git_date=$(date --date "@$(git --git-dir "${GO_SRC_PATH}/.git" log -1 --pretty='%at')" +'%Y%m%d.%H%M%S')
    git_sha=$(git --git-dir "${GO_SRC_PATH}/.git" log -1 --pretty='%h')
    VERSION="0.${git_date}~${git_sha}"
    RPM_RELEASE_VERSION=0
    RPM_VERSION="$VERSION"
fi
REF=$(git --git-dir "${GO_SRC_PATH}/.git" rev-parse HEAD)

export REF
export RPM_RELEASE_VERSION
export RPM_VERSION
export VERSION

(set -x; yum-builddep -y SPECS/containerd.spec; rpmbuild -ba SPECS/containerd.spec)
