#!/usr/bin/env bash

set -e

VERSION="$(git -C "${GO_SRC_PATH}" describe --tags)"
# Check if we're on a tagged version, change VERSION to dev build if not
if ! git -C "${GO_SRC_PATH}" describe --exact-match HEAD >/dev/null 2>&1; then
    git_date=$(date --date "@$(git -C "${GO_SRC_PATH}" log -1 --pretty='%at')" +'%Y%m%d.%H%M%S')
    git_sha=$(git -C "${GO_SRC_PATH}" rev-parse --short HEAD)
    VERSION="0.${git_date}~${git_sha}"
fi
export VERSION
REF=$(git -C "${GO_SRC_PATH}" rev-parse HEAD)
export REF

(set -x; rpmbuild -ba SPECS/containerd.spec)
