#!/usr/bin/env sh

#   Copyright 2018-2020 Docker Inc.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# shellcheck disable=SC1090
. "$(dirname "$0")/.helpers"

set -e

VERSION="$(git --git-dir "${GO_SRC_PATH}/.git" describe --tags | sed 's/^v//')"
# Check if we're on a tagged version, change VERSION to dev build if not
if ! git --git-dir "${GO_SRC_PATH}/.git" describe --exact-match HEAD > /dev/null 2>&1; then
	git_date=$(date --date "@$(git --git-dir "${GO_SRC_PATH}/.git" log -1 --pretty='%at')" +'%Y%m%d.%H%M%S')
	git_sha=$(git --git-dir "${GO_SRC_PATH}/.git" log -1 --pretty='%h')
	VERSION="${git_date}~${git_sha}"
	# prepend a `0` so it'll never be greater than non-dev versions
	cat > debian/nightly.changelog <<- EOF
		$(control_field Package) (0.${VERSION}-1) development; urgency=medium

		  * Release for ${git_sha}

		 -- $(control_field Maintainer)  $(date --rfc-2822)

	EOF
	cat debian/changelog >> debian/nightly.changelog
	cat debian/nightly.changelog
	mv debian/nightly.changelog debian/changelog
fi

REF=$(git --git-dir "${GO_SRC_PATH}/.git" rev-parse HEAD)
export REF
export VERSION

(
	set -x
	dpkg-buildpackage -uc -us
)

DIST_ID="$(. /etc/os-release; echo "${ID}")"
DIST_VERSION=$(lsb_release -sc)
ARCH=$(dpkg --print-architecture)
DEST_DIR="/build/${DIST_ID}/${DIST_VERSION}/${ARCH}/"
mkdir -p "${DEST_DIR}"
mv -v ../*.deb "${DEST_DIR}"

if [ "${DIST_VERSION}" = 'n/a' ]; then
	# Give a more useful error message if we failed to get the "codename",
	# which can be the case on Debian "unstable" releases. For more background:
	# https://github.com/docker/containerd-packaging/pull/213#issuecomment-782172567
	echo "Failed to get release codename"
	exit 1
fi

# Only create an archive if env variable is specified
if [ -n "${CREATE_ARCHIVE}" ]; then
	tar -C /build -cvzf "/archive/${DIST_ID}-${DIST_VERSION}-${ARCH}.tar.gz" "${DIST_ID}/${DIST_VERSION}/${ARCH}"
fi
