#!/usr/bin/env sh

#   Copyright 2018-2020 Docker Inc.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Select the default version of runc based on the containerd source if no
# RUNC_REF is set manually.
#
# See the install-runc script in the containerd repository:
# https://github.com/containerd/containerd/blob/v1.5.0/script/setup/install-runc#L24-L27
runc_version() {
	if [ -n "${RUNC_REF}" ]; then
		# just a safe-guard if this script is called when RUNC_REF was already set.
		echo "${RUNC_REF}"
		>&2 echo "INFO: using runc version (${RUNC_REF}) from RUNC_REF."
		return
	fi

	# shellcheck disable=SC2164
	repo_abspath="$(cd -- "$(dirname -- "$0")/.." > /dev/null 2>&1; pwd -P)"
	containerd_src_dir="${repo_abspath}/src/github.com/containerd/containerd"

	if [ -f "${containerd_src_dir}/script/setup/runc-version" ]; then
		# starting with v1.5.0-beta.4 and up, and v1.4.5, containerd specifies
		# the version of runc to use in script/setup/runc-version.
		runc_ref=$(cat "${containerd_src_dir}/script/setup/runc-version")
		>&2 echo "INFO: detected runc version (${runc_ref}) from script/setup/runc-version"
		echo "${runc_ref}"
		return
	fi

	# if all else fails
	>&2 echo "WARNING: unable to detect runc version, using HEAD"
	echo "HEAD"
}

runc_version
