#!/usr/bin/env sh

#   Copyright 2018-2020 Docker Inc.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

IMAGE=$1
potential=$(docker run --rm -i "$IMAGE" cat /etc/os-release 2> /dev/null | grep "^ID=" | cut -d'=' -f2 | sed 's/"//g')

if [ -z "$potential" ]; then
	exit 1
fi

case $potential in
	# Since we use both opensuse and sles to compile these
	*sles* | *suse*)
		echo suse
		;;
	*)
		echo "$potential"
		;;
esac
