#!/usr/bin/env bash

IMAGE=$1
potential=$(docker run --rm -i "$IMAGE" cat /etc/os-release 2>/dev/null | grep "^ID=" | cut -d'=' -f2 | sed 's/"//g')

if [ -z "$potential" ]; then
    exit 1
fi

case $potential in
    # Since we use both opensuse and sles to compile these
    *sles*|*suse*)
        echo suse
        ;;
    *)
        echo "$potential"
        ;;
esac
