#!/usr/bin/env sh

#   Copyright 2018-2020 Docker Inc.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

GOVERSION=${GOVERSION:-1.12.16}
HOST_ARCH=${HOST_ARCH:-$(uname -m)}
DL_ARCH=${HOST_ARCH}

# Why do they name them differently than their `uname -m` counterparts?
# ¯\_(ツ)_/¯
case $HOST_ARCH in
	x86_64)
		DL_ARCH="amd64"
		;;
	aarch64)
		DL_ARCH="arm64"
		;;
	armv7l)
		DL_ARCH="armv6l"
		;;
esac

echo "https://dl.google.com/go/go${GOVERSION}.linux-${DL_ARCH}.tar.gz"
