#!/usr/bin/env bash

#   Copyright 2018-2020 Docker Inc.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

set -e

SPEC_FILE="rpm/containerd.spec"
export SPEC_FILE
source scripts/.rpm-helpers

VERSION="$1"
if [ -z "$VERSION" ]; then
    echo "Usage: $0 <VERSION>"
    exit 1
fi
RPM_VER_BITS=$(gen-rpm-ver-bits "${VERSION}")
RPM_VERSION=$(echo "${RPM_VER_BITS}" | cut -f1 -d' ')
RPM_RELEASE_VERSION=$(echo "${RPM_VER_BITS}" | cut -f2 -d' ' | sed 's/\.[0-9]*$//')
RPM_ITERATION=1

while grep "$RPM_VERSION-$RPM_RELEASE_VERSION.$RPM_ITERATION" "${SPEC_FILE}" >/dev/null 2>&1;do
    ((++RPM_ITERATION))
done

cat > rpm/new.changelog << EOF
* $(date +"%a %b %d %Y") $(git config user.name) <$(git config user.email)> - $RPM_VERSION-$RPM_RELEASE_VERSION.$RPM_ITERATION
- TODO: Insert release changes here

EOF

cleanup() {
    rm rpm/new.changelog
    rm "${SPEC_FILE}.bak"
}

trap cleanup EXIT

sed -i'.bak' '/%changelog/ r rpm/new.changelog' "${SPEC_FILE}"
