#!/usr/bin/env bash

#   Copyright 2018-2020 Docker Inc.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

source scripts/.helpers

VERSION=$1
if [ -z "$VERSION" ]; then
    echo "Usage: $0 <VERSION>"
    exit 1
fi
URGENCY=${URGENCY:-medium}

NEW_DEB_VERSION=${VERSION//-/\~}
DEB_ITERATION=1

while grep "$NEW_DEB_VERSION-$DEB_ITERATION" debian/changelog >/dev/null 2>&1;do
    ((++DEB_ITERATION))
done

cat > debian/new.changelog <<-EOF
$(control_field Package) (${NEW_DEB_VERSION}-${DEB_ITERATION}) release; urgency=${URGENCY}

  * TODO: Insert release changes here

 -- $(git config user.name) <$(git config user.email)>  $(date --rfc-2822)

EOF
cat debian/changelog >> debian/new.changelog
cat debian/new.changelog
(set -x; mv debian/new.changelog debian/changelog)
