#!/usr/bin/env bash

source scripts/.helpers

VERSION=$1
if [ -z "$VERSION" ]; then
    echo "Usage: $0 <VERSION>"
    exit 1
fi
URGENCY=${URGENCY:-medium}

NEW_DEB_VERSION=${VERSION//-/\~}
DEB_ITERATION=1

while grep "$NEW_DEB_VERSION-$DEB_ITERATION" debian/changelog >/dev/null 2>&1;do
    ((++DEB_ITERATION))
done

cat > debian/new.changelog <<-EOF
$(control_field Package) (${NEW_DEB_VERSION}-${DEB_ITERATION}) release; urgency=${URGENCY}

  * TODO: Insert release changes here

 -- $(git config user.name) <$(git config user.email)>  $(date --rfc-2822)

EOF
cat debian/changelog >> debian/new.changelog
cat debian/new.changelog
(set -x; mv debian/new.changelog debian/changelog)
